select * from addresses;
select * from coupons;
select * from menu_items;
select * from order_items;
select * from orders;
select * from payments;
select * from restaurants;
select * from reviews;
select * from users;